### ISSUE TITLE
Issues in docker image

### ISSUE THREAD

**Issue by jkiddo** [kirei/hcert#7]
The following doesn't look entirely correct:

```
docker run -it --rm hcert
curl -o hcert_schema.yaml https://raw.githubusercontent.com/ehn-digital-green-development/hcert-schema/main/eu_hcert_v1_schema.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5853  100  5853    0     0  16818      0 --:--:-- --:--:-- --:--:-- 16867
python3 schemacheck.py --input hcert_example_minimal.json hcert_schema.yaml
Checking schema hcert_schema.yaml
Checking input hcert_example_minimal.json
python3 schemacheck.py --input hcert_example_typical.json hcert_schema.yaml
Checking schema hcert_schema.yaml
Checking input hcert_example_typical.json
python3 schemacheck.py --input hcert_example_large.json   hcert_schema.yaml
Checking schema hcert_schema.yaml
Checking input hcert_example_large.json
sh test.sh
Signing hcert_example_minimal.json
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/hcert-6WcazSRI-py3.9/bin/hcert", line 5, in <module>
    main()
  File "/tmp/hcert/cli.py", line 200, in main
    args.func(args)
  File "/tmp/hcert/cli.py", line 30, in command_sign
    private_key = read_cosekey(args.key, private=True)
  File "/tmp/hcert/cwt.py", line 41, in read_cosekey
    jwk_dict = json.load(jwk_file)
  File "/usr/lib64/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Verify hcert_example_minimal.json
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/hcert-6WcazSRI-py3.9/bin/hcert", line 5, in <module>
    main()
  File "/tmp/hcert/cli.py", line 200, in main
    args.func(args)
  File "/tmp/hcert/cli.py", line 62, in command_verify
    public_key = read_cosekey(args.key, private=False)
  File "/tmp/hcert/cwt.py", line 41, in read_cosekey
    jwk_dict = json.load(jwk_file)
  File "/usr/lib64/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Signing hcert_example_typical.json
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/hcert-6WcazSRI-py3.9/bin/hcert", line 5, in <module>
    main()
  File "/tmp/hcert/cli.py", line 200, in main
    args.func(args)
  File "/tmp/hcert/cli.py", line 30, in command_sign
    private_key = read_cosekey(args.key, private=True)
  File "/tmp/hcert/cwt.py", line 41, in read_cosekey
    jwk_dict = json.load(jwk_file)
  File "/usr/lib64/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Verify hcert_example_typical.json
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/hcert-6WcazSRI-py3.9/bin/hcert", line 5, in <module>
    main()
  File "/tmp/hcert/cli.py", line 200, in main
    args.func(args)
  File "/tmp/hcert/cli.py", line 62, in command_verify
    public_key = read_cosekey(args.key, private=False)
  File "/tmp/hcert/cwt.py", line 41, in read_cosekey
    jwk_dict = json.load(jwk_file)
  File "/usr/lib64/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Signing hcert_example_large.json
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/hcert-6WcazSRI-py3.9/bin/hcert", line 5, in <module>
    main()
  File "/tmp/hcert/cli.py", line 200, in main
    args.func(args)
  File "/tmp/hcert/cli.py", line 30, in command_sign
    private_key = read_cosekey(args.key, private=True)
  File "/tmp/hcert/cwt.py", line 41, in read_cosekey
    jwk_dict = json.load(jwk_file)
  File "/usr/lib64/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Verify hcert_example_large.json
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/hcert-6WcazSRI-py3.9/bin/hcert", line 5, in <module>
    main()
  File "/tmp/hcert/cli.py", line 200, in main
    args.func(args)
  File "/tmp/hcert/cli.py", line 62, in command_verify
    public_key = read_cosekey(args.key, private=False)
  File "/tmp/hcert/cwt.py", line 41, in read_cosekey
    jwk_dict = json.load(jwk_file)
  File "/usr/lib64/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by jschlyter** [comment]
Have you rebuilt the container? If I clone the repository fresh and build the container everything runs here.

**Comment by jkiddo** [comment]
Hmmm- .... clean clone did the job
